NASM := nasm -f elf32
SHELL_IN := src/rev_shell.nasm
SHELL_OBJ := bin/shell_obj
SHELL_OUT := bin/shell
BIND_EXE := bin/revshell
BIND_IN := src/shellcode.c
LINKER := ld -melf_i386
CC := gcc -fno-stack-protector -z execstack -m32
